---
title: 'Outlook: Linked Data and the Semantic Web'
teaching: 10
exercises: 2
---

::::::::::::::::::: callout

:construction: **UNDER CONSTRUCTION** :construction:

:::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::: questions 

- How do you write a lesson using R Markdown and `{sandpaper}`?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Explain how to use markdown with the new lesson template
- Demonstrate how to include pieces of code, figures, and nested challenge blocks

::::::::::::::::::::::::::::::::::::::::::::::::


## Linked Data & the Semantic Web

Most search engines are based on keywords:
<ul>
  <li>results are high recall and low precision</li>
  <li>results are highly sensitive to vocabulary</li>
  <li>results are single human-readable web pages</li>
  <li>**results do not support logical reasoning and query answering**</li>
</ul>

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: Linked Data & JSON Ld

**Slide set**: <i>not provided in slide set</i><br>
**Time estimate**: 5 min

:construction: **UNDER CONSTRUCTION** :construction:

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: Graph Data Bases & the Semantic Web

**Slide set**: <i>not provided in slide set</i><br>
**Time estimate**: 5 min

:construction: **UNDER CONSTRUCTION** :construction:

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**The term “Semantic Web” refers to <a href="https://www.w3.org/standards/semanticweb/" target="_blank">W3C’s</a> vision of a Web of Linked Data.**

It provides a way for machines to be able to process and understand the data that they were only to display on the traditional Web. It is a vision for the future Web (a web of meaning — semantics); originally defined by Tim Berners-Lee. The Semantic Web is not a separate Web, but an extension of the current one. In the Semantic Web, metadata are invisible as people read the page, but they're clearly visible to computers.

But this is another story and shall be told another time...

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: callout 
The goal of a Semantic Web is to **make computers perform more of the tedious work involved in finding, sharing and combining information on the Web efficiently.**
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



::::::::::::::::::::::::::::::::::::: keypoints 

- Use `.md` files for episodes when you want static content
- Use `.Rmd` files for episodes when you need to generate output
- Run `sandpaper::check_lesson()` to identify any issues with your lesson
- Run `sandpaper::build_lesson()` to preview your lesson locally

::::::::::::::::::::::::::::::::::::::::::::::::

