---
title: 'Getting Started'
teaching: 2
exercises: 10
---
:::::::::::::::::::::::::::::::::::::: questions 

- What could the subject of the data set be?
- What is challenging for understanding the data?
- What would you have needed to draw conclusions on the data?

::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::: objectives

- Getting familiar with the example data set.
- Facing a well-known challenge, when exploring a data set. 
:::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: challenge
## Challenge 0: What do you see?

Your collaborators sent you a link to one of their tabular data sets with the request to inspect and comment on the data collected.

- Download the data: <a href="./files/exampleDataObject.csv">exampleDataObject.csv</a> (.csv file, separator: ";") 
- Open .csv with your day-to-day data tool (Python, MS Excel, R, Matlab, etc.)
- Inspect the data

- Ask yourself the following questions:
  - Do you get information out of the data?
  - Which challenges do you face?
  - Is context missing?
  
- Note your answers. We will discuss your statements in the lesson

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: hint
**Important:** There is no right or wrong in this task. Just note down whatever comes to your mind!
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor 

## Creator recommendation
This challenge is meant to get the learners into the mindset of the lesson by giving them a (usually) familiar problem: **unsufficiently annotated, uninterpretable data**.

Send this challenge to the learners before the lesson starts. During the warm-up and introduction session of your lesson, ask the learners to briefly share their experiences with the data set. You can use the questions in the overview as a guideline.

We recommend collecting the learners' statements in bullet points on a white board or shared document. After the introduction session, an adhoc summary of the statements can be used to lead over to the lesson topic.

**The subject of the example data will be revealed after the introductory lecture on "What is data?" and bridges over to the topic of metadata.**

::::::::::::::::::::::::::::::::::::::::::::::::