---
title: Instructor guide
---

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: checklist
## Before the lesson

- send the link to the "**Episode 1: Getting started**" 2-3 days before the lesson starts. 
- prepare **group handouts**. You can find a Markdown template here: LINK
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

## Lesson schedule

<div class="overview card">
  <h2 class="card-header">Day 1</h2>
  <div class="row g-0">
|<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> | Episode | Content |
| ----- | :---: | ------------------------------- |
| 35 min | [0](#episode-0-housekeeping) | Introduction bla bla bla lorem impsum bla bla blank !!! build this table based on the content of the instructor guide !!! Don't forget to place the anchors !!! |
| 65 min | [2](#episode-2-data-metadata) |  |
| 15 min |  | :coffee: Break :coffee: |
</div>
</div>


## Episode 0: Housekeeping
<div class="overview card">
  <h2 class="card-header">Episode Schedule</h2>
  <div class="row g-0">
|<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> | Content type | Title |
| :-----: | ---------- | ----------------------------------------- |
| 5 min | **Lecture** | [Instructor introduction](#accordionInstructor1) |
| 28 min | **Group activity** | [Learner introduction](#accordionInstructor2) |
| 2 min | **Lecture** | [Lesson scope & structure](#accordionInstructor3) |
</div>
</div>

**Total time:** 35 min <br>
**Teaching methods:** direct teaching, group activity, discussion <br>
**Learning types:** acquisition, collaboration <br><br>

**Learning Objectives:**<br>
<u>REMEMBER</u><br> 
<ul>
  <li>The participants are aware of the tasks and contact information of the hosting organization.</li></ul>
<u>UNDERSTAND</u><br> 
<ul>
  <li>The learners get to know the teacher and the other participants. an open and collaborative working atmosphere is created.</li>
</ul>

**Description:**<br>
Start the lesson by introducing the learners to the instructors, i.a. the hosting organization, and each other.
Ask the learners to briefly introduce themselves.  
Outline the scope and schedule of the lesson.

**Talking Points:**

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: Instructor introduction

**Slide set**: <i>not provided in slide set</i><br>
**Time estimate**: 5 min

- Personal instructor introduction
- Institutional setting if applicable

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Group activity: Learner introduction

**Time estimate**: 28 min
**Material**: whiteboard or shared notes

Guiding questions could be:

<ul>
  <li>What is your name?</li>
  <li>What is your research topic? (especially helpful when working with a research field heterogenous group of learners)</li>
  <li>How did you approach the example data object?</li>
  <li>What was easy to identify in the data object?</li>
  <li>What was hard and why?</li>
  <li>What would have helped to understand the data better?</li>
  <li>Based on your experiences, what do you suspect the data to describe?</li>
</ul>
While the learners share their ideas about the example data object, take notes of their answers. These notes can be retrieved at later stages of the lesson, when the example data object is set in context and better understood by the learners to show the progress.

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: Lesson scope & structure

**Slide set**: <i>not provided in slide set</i><br>
**Time estimate**: 2 min

- brief overview over the schedule, structure and scope of this lesson

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

## Episode 2: Data & Metadata
<div class="overview card">
  <h2 class="card-header">Episode Schedule</h2>
  <div class="row g-0">
|<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> |Content type | Title |
| :-----: | ---------- | ----------------------------------------- |
| 30 min | **Lecture** | [What is data?](#accordionInstructor4)<br>[The example data object](#accordionInstructor5)<br>[What is metadata?](#accordionInstructor6)<br>[Descriptive, administrative, structural metadata](#accordionInstructor7) |
| 15 min | **Challenge** | [Real World Metadata](#accordionInstructor8) |
| 10 min | **Lecture** | [Metadata in the scientific context](#accordionInstructor9)  |
| 10 min | **Guided confrontation** | [Metadata in scientific publications](#accordionInstructor10) |

</div>
</div>

**Total time:**  65 min<br>
**Teaching methods:**  direct teaching, guided confrontation<br>
**Learning types:**  acquisition, investigation, discussion<br><br>

**Learning Objectives:**<br>
<u>UNDERSTAND</u><br> 
<ul>
  <li>The learners get familiar with the example data object.</li>
  <li>The learners recognize and describe examples of (meta)data.</li></ul>
<u>REMEMBER</u><br> 
<ul>
  <li>The learners name examples for best / worst practice situations in research (meta)data handling.</li>
</ul>

**Description:**<br>
The learners get an introduction into data and metadata in everyday life and research contexts. Descriptive, administrative, and structural metadata are distinguished. The learners conduct a guided online search (URLs are provided) and explore the metadata tagging in selected web pages. Good (enough) and worst practices of metadata annotation will be covered in the fina talk of this module. The presentation is complemented with a live demonstration, collaboratively extracting metadata from scientific publications.  

**Talking Points:**

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: What is data?

**Slide set**: 3 - 14<br>
**Time estimate**:

- What is data? (<i>direct this question to the audience and allow them to just shout in. Wait a little, it might be quiet</i> :wink:)
- We start with an example: Imagine a satellite transmitting data back to earth.
- This is what actually arrives at the machine receiving the transmission...
- just a concatenation of signs...
- we call these **glyphs**. To a human being, this sequence of glyphs is not understandable and it needs some processing by a machine to make it interpretable for humans. And this is data...
- a **potentially informative object**. 
- If the data is now processed by the receiving machine, it will be converted in this picture. (<i>The satellite image shows the city center of Cologne, Germany. Feel free to substitute it with a place your learners are familiar with and activate them by asking "Does anyone know, what is depicted?"</i>) In this processed form, the data becomes human-readable. In information science, this is what we call information.
- Knowledge is intrinsified information. For example, knowing where on the image the cathedral is located.
- The highest level of information content is wisdom, which means putting the acquired knowledge into context, the bigger picture. You might use the satellite image to navigate between to locations, for example. Naturally, as researchers, we strive to reach wisdom with our work.
- We have seen, that the information content increases by adding context, meaning, and insight to data.
-The take-away message is: Data is **potential information** and needs to be processed and contextualized** to make it accessible for the human audience.

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: The example data object

**Slide set**: 15 - 19<br>
**Time estimate**:

- Now back to the example data you received from us. (<i>Here you can reflect on some of the statements made during the introduction session.</i>) What actually is represented in the data is this...
- (<i>Empty slide: open <a href="https://www.youtube.com/watch?v=KeKIBSN2F5c" target="_blank">https://www.youtube.com/watch?v=KeKIBSN2F5c</a> in a new tab or window and play the video. We start the video from 0:30. </i>)
- Shown in the data is the ride time (t)...
- the biomechanical acceleration of a human body during the rollercoaster ride in x, y, and z axis... (<i>Yes, the image of the toy bunny is really taken from a peer reviewed journal publication.</i>)
- and a boolean value, stating whether a scream of the test person could be detected or not.
- (<i>allow some time for questions</i>)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: What is metadata?

**Slide set**: 20 - 28<br>
**Time estimate**:

- What is metadata? (<i>Direct this questions to the learners and wait for them to reply. They might come up with the generic "Data about data".</i>)
- Often metadata is described as "data about data", or - as Merriam Webster puts it - "metadata is data that provides information about other data". But this is extremely unspecific.
- If you look a bit further, you can find more detailed description of the term "metadata". Admittedly, these text are seldomly...
- fun to read.
- Let's start - again - with an example. Let's say, you are looking for an informative book about the topic of metadata and decide to look for recommendations online...
- your search will result in about 1,5 million results. But you remember a colleague, that has recently talked about a very good book on metadata...
- you ask him about it and he gives you a well-meaning description of said book. "It is black and the title is 'metadata'. It was written by Jeff... Jeff... Something."
- Okay, this is not really precise but you take these information to your favourite search engine and you will most likely come up with this ...
- book. Metadata by Jeffrey Pomerantz published in the MIT Press Essential Knowledge series. So far, you have absolutely no idea about the content of the book - the actually data that is hold by it. However, with just a few clues on the title, author, and design, you can identify the ressource. You did this by using "metadata". Let's stay with this example for a bit and take a look inside... 

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: Descriptive, administrative, structural metadata

**Slide set**: 29 - 37<br>
**Time estimate**:

- On one of first pages, you will find a lot of information about the book...
- You will get information on author, publisher, keywords and so on, that are descriptive in nature and can help you - or librarians - to successfully identify this specific book. Among these is a very important descriptor...
- The persistent identifier. In the example of a book, this is the ISBN number. Whenever you look up this number, the result will unambiguously point to this specific title.
- Furthermore, you will get information about how the book is administered: How it is distributed, who is responsible for its distribution and which conditions need to apply.
- You can also find information on legal conditions that apply to this resource, such as copyright issues and the terms of distribution. Legal information can be considered as a subset of administrative information.
- And - really important - you will get a precise idea about the book's structure and how you can navigate it: the chapters, its general content and how it is distributed over the pages. But still: we have not yet read a single word, that actually delivers the content of the book - its data.
- So, metadata - or metainformation - is more or less structured data, that contains information about characteristics of other data (objects).
- Let's briefly reflect on the types of metadata, that we came across so far, before we apply these concepts in the first challenge for today: 
  - descriptive metadata holds information about the intellectual content, such as title, author, abstract...
  - administrative metadata specifies how a resource is managed. This can be terms of distribution and copyright information. Regarding published data, this also applies to technical information on the files included in a data set or versioning...
  - structural metadata describe, for example chapters in a book, file in a data set, or software components.
- (<i>allow some time for questions</i>)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Challenge 2: Real world metadata

**Slide set**: 38

**Time:** 15 min 

**Challenge type:** guided confrontation, individual investigation, discussion

**Objective:** <br>
The learners experience a real world example of functional metadata applications and practice their acquired knowledge on metadata types.

**Implementation:** <br>
We recommend using a pre-structured, collaborative document 
(whiteboard or notepad) to collect the participants' results.
Allow for some time for the learners to navigate the websites and explore the metadata in the source code individually (ca. 8 min). Open the source code of one website in the browser and share the screen. Talking points for the guided confrontation can be: 
<ul>
  <li>different types of targets (e.g. `twitter:`, `robots:`)</li>
  <li>different contexts (e.g. `dc:`, `og:`); don't go to deep in this topic and just teaser the existence of metadata standards and references</li>
  <li>**Fun fact:** *The Guardian* regularly uses a comment in the `head` of their html documents to advertise IT jobs :grin: </li>
</ul>

**White board:** <a href="../../../episodes/files/exampleChallenge1Whiteboard.pdf">example set-up</a>

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
## Lecture: Metadata in the scientific context

**Slide set**: 39 - 56<br>
**Time estimate**: 10 min

- Now let's shift our focus on metadata annotation in the scientific context.
- I'm sure many of us have been in a similar situation. You start a new project that is based on the work of your predecessor or collaborators and you are supposed to start with reproducing the published results...
- You take a look at the accompnying publication and the data looks neat...
- But as soon as you open the underlying data sets, understanding the process on how this data was acquired is not so straight forward anymore. The variables might be hard to understand, there might be missing values, and the data cleaning is not necessarily apparent.
- So you take a look at the experiment's documentation...
- A study by Monya Baker, that was published in Nature in 2016 was able to show, that more than 70% of researchers have tried and failed to reproduce another scientis's experiments. And more than half have even failed to reproduce their own experiments.
- The worst practice that you can encounter in your scientific life is surely data, saved under an inexplicit file name with no documentation whatsoever.
- Slightly better practice are lab notes, which are still widely used as the go-to documentation method in experimental scientific areas. Using lab notes as documentation method, you can facilitate the findability by assigning meaningful file names to your data. However...
- lab notes come with various disadvantages. Lab notes are usually taken continuously and over the course of a 3-year contract, several hundred pages of lab notes can accumulate.
- so even though lab notes allow for some kind of documentation, they are largely unstructured and subjective, rarely following templates or guidelines. The continous note taking makes the documentation hard to retrieve. They are physically seperated from the data they describe and remain in the hand of the experimentator or institution hosting the experiments, which makes them hard to share. And let's admit it, handwriting can be a pain to read.
- One way to store your documentation with your data, is README-style metadata. 
- Just like taking lab notes, Readme-style files can be subjectively written natural text documents. 
- You can also find templates for Readme-style metadata records. Sticking to these templates will allow for increased structure in your documentation records. Now that we document our data digitally, we have increased options to link the metadata record to the described data set, for example by naming them accordingly...
- if you now want to find the results of a specific experiment on your computer, a local keyword search can help you to identify the data set.
- To sum up, digital documentation of your metadata in form of Readme-style metadata records, facilitates the linkage of data and metadata, allows for local searchability and increased readability, and the digital nature of the Readme file simplifies targeted sharing of the documentation. However, these records are still rather unstructured and subjective, and only allow for keyword searches.
- If you want to have a look on a well-designed template for Readme-style metadata records, a recommended link is provided in the Episode description.
- (<i>allow some time for questions</i>)

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor
# Guided confrontation: Metadata in scientific publications

**Slide set:** 57

**Time:** 10 min

**Type:** guided confrontation, collaboration

**Objective:** <br>
The learners apply their acquired knowledge about metadata identification and types on a familiar work situation.

**Implementation:** <br>
<ul>
  <li>select a scientific journal publication of your liking (could be related to the research field of the learners, if the group is homogeneous in this regard.)</li>
  <li>share the journal on your screen</li>
  <li>with the whole group of learners, find the "hidden" metadata in the publication and sort the findings into the metadata types (descriptive, administrative, structural)</li>
</ul>

**Creator's recommendation**: <br>
Use a white board application to display the journal publication. This allows for simultaneous highlighting / annotation of the findings and thus gives a visual response and documentation of the discussion. 
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

<br><br>

---

### :coffee: 15 min Break :coffee:

---

## Episode 3: Structured metadata - from Markup to JSON

## Episode 4. Enabling technologies with schemas and standards

## Episode 5: (Web) Location & Identifiers

## Episode 6: Outlook - Linked Data